version: "3.8"

services:
  api:
    container_name: api_db
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - 3000:3000
  ui:
    build:
      context: .
      dockerfile: ui.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - api